# Generated by Django 5.2.4 on 2025-07-30 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('CSE', 'Computer Science Engineering'), ('AIML', 'Artificial Intelligence and Machine Learning'), ('AIDS', 'Artificial Intelligence and Data Science'), ('CSBS', 'Computer Science and Business Systems'), ('ECE', 'Electronics and Communication Engineering'), ('EEE', 'Electrical and Electronics Engineering'), ('CCE', 'Computer and Communication Engineering'), ('MECH', 'Mechanical Engineering'), ('IT', 'Information Technology')], default='CSE', max_length=4)),
                ('year', models.CharField(choices=[('I', 'First Year'), ('II', 'Second Year'), ('III', 'Third Year'), ('IV', 'Fourth Year')], default='I', max_length=4)),
                ('club', models.CharField(choices=[('Harmonix', 'Harmonix'), ('Groovex', 'Groovex')], default='Harmonix', max_length=100)),
                ('role', models.CharField(choices=[('Vocalist', 'Vocalist'), ('Guitarist', 'Guitarist'), ('Drummer', 'Drummer'), ('Keyboardist', 'Keyboardist'), ('Bassist', 'Bassist'), ('Dancer', 'Dancer')], default='Vocalist', max_length=100)),
                ('position', models.CharField(choices=[('Member', 'Member'), ('President', 'President'), ('Vice President', 'Vice President'), ('Secretary', 'Secretary'), ('Joint-Secretary', 'Joint-Secretary')], default='Member', max_length=100)),
                ('user_role', models.CharField(choices=[('Admin', 'Admin'), ('User', 'User')], default='User', max_length=100)),
                ('event_counts', models.IntegerField(default=0)),
                ('present_days', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('club', models.CharField(choices=[('Harmonix', 'Harmonix'), ('Groovex', 'Groovex')], default='Harmonix', max_length=100)),
                ('members_participated', models.ManyToManyField(blank=True, related_name='events_participated', to='app.membermodel')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_present', models.BooleanField(default=False)),
                ('club', models.CharField(choices=[('Harmonix', 'Harmonix'), ('Groovex', 'Groovex')], default='Harmonix', max_length=100)),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.membermodel')),
            ],
            options={
                'unique_together': {('member', 'date')},
            },
        ),
    ]
