# Generated by Django 5.2.4 on 2025-08-08 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='membermodel',
            name='present_days',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
